apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.name }}-pv
  labels:
    app: {{ .Values.mysql.name }}
spec:
  storageClassName: {{ .Values.mysql.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.mysql.persistentVolume.storage }}
  volumeMode: {{ .Values.mysql.persistentVolume.volumeMode }}
  accessModes: {{ .Values.mysql.persistentVolume.accessModes }}
  hostPath: 
    path: {{ .Values.mysql.persistentVolume.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-claim
  labels:
    app: {{ .Values.mysql.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.mysql.persistentVolume.storage }}
  accessModes: {{ .Values.mysql.persistentVolume.accessModes }}
  storageClassName: {{ .Values.mysql.persistentVolume.storageClassName }}