mysql:

  name: mysql

  persistentVolume:
    storageClassName: manual
    storage: 5Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /var/lib/mysql

  deployment:
    image: mysql:8.0
    containerPort: 3306
    mountPath: /var/lib/mysql

petclinic:

  name: spring-petclinic

  deployment:
    replicas: 3
    image: dejanakop/spring-petclinic-main:13d63d2
    containerPort: 8080

  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080