name: Destroy Self-Hosted Runner

on:
  workflow_dispatch:

jobs:

  terraform_destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-actions-runner/terraform
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Download .tfvars file
        run: gsutil cp ${{ secrets.TF_VARS_PATH }} ./terraform.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy \
          -var="github_pat=${{ secrets.GH_PAT }}" \
          --auto-approve
