name: Infrastructure

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  terraform_plan:
  
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./main/terraform

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Download .tfvars file
        run: gsutil cp ${{ secrets.MAIN_TF_VARS_PATH }} ./terraform.tfvars

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Configure GKE credentials
        run: |
          gcloud container clusters get-credentials {{ secrets.CLUSTER_NAME }}

      - name: Terraform Init
        run: terraform init

      - name: Validate .tf files
        run: terraform validate

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
