name: Plan Infrastructure

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  ENVIRONMENT: "dev"

jobs:

  terraform_check:
  
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./main/env/${{ env.ENVIRONMENT }}/

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Download .tfvars file
        run: gsutil cp ${{ secrets.MAIN_TF_VARS_PATH }} ./terraform.tfvars

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Validate .tf files
        run: terraform validate

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Set Up tflint
        uses: terraform-linters/setup-tflint@v6

      - name: Init tflint
        run: tflint --init

      - name: Run tflint
        run: tflint --recursive --minimum-failure-severity=error

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true

  terraform_plan:

    needs: [ "terraform_check" ]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./main/env/${{ env.ENVIRONMENT }}/

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Download .tfvars file
        run: gsutil cp ${{ secrets.MAIN_TF_VARS_PATH }} ./terraform.tfvars

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
