name: Create Self-Hosted Runner

on:
  workflow_dispatch:

jobs:

  terraform:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-actions-runner/terraform
    outputs:
      runner_ip: ${{ steps.output.outputs.runner_ip }}
        
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Download .tfvars file
        run: gsutil cp ${{ secrets.TF_VARS_PATH }} ./terraform.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Validate .tf files
        run: terraform validate

      - name: Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: Terraform Output
        id: output
        run: |
          echo "runner_ip=$(terraform output -raw runner_ip)" >> $GITHUB_OUTPUT

  ansible:

    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-actions-runner/ansible

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Gcloud Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Add SSH key
        run: | 
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Install Ansible
        run: pip install ansible

      - name: Create inventory.ini
        run: |
          TARGET_HOST=${{ needs.terraform.outputs.runner_ip }}
          echo "
          [webservers]
          ${TARGET_HOST}" > inventory.ini

      - name: Create Ansible Config file
        run: |
          echo "
          [defaults]
          ansible_python_interpreter=/usr/bin/python3
          inventory=inventory.ini
          host_key_checking=False
          private_key_file=~/.ssh/key
          " > ansible.cfg

      - name: Run Ansible Playbook
        run: ansible-playbook runner_setup.yaml -i inventory.ini --extra-vars "ansible_user=${{ secrets.USER }}"
